Thrown exception: FileExistsError('FNFError')
Variables:
a = 4
b = 554

